# -*- coding: utf-8 -*-
"""week4-A108060110-許家寧.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CqJca1yWAEIwbPAwvpmUzzC6-mQffbBF
"""

print("Hello World")
