# -*- coding: utf-8 -*-
"""week5chatbox模式一.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F8UQidnxa-uN6KZRINKcJg473IDVF166
"""

print("許家寧")
print("19歲")
print("52kg")